packages:
  - core
  - cli
  - actions
  - commands/*
  - docs

catalogs:
  default:
    "@actions/core": ^1.11.1
    "@actions/github": ^6.0.0
    "@nestjs/cli": ^11.0.0
    "@nestjs/common": ^11.0.1
    "@nestjs/config": ^4.0.2
    "@nestjs/core": ^11.0.1
    "@nestjs/event-emitter": ^3.0.1
    "@nestjs/platform-express": ^11.0.1
    "@nestjs/schematics": ^11.0.0
    "@nestjs/swagger": ^11.2.6
    "@nestjs/testing": ^11.0.1
    "@swc/cli": ^0.6.0
    "@swc/core": 1.15.3
    "@types/express": ^5.0.0
    "@types/node": ^22.15.0
    "@types/supertest": ^6.0.2
    "@vercel/ncc": ^0.38.3
    class-transformer: ^0.5.1
    class-validator: ^0.14.3
    nest-commander: ^3.20.1
    oxfmt: ^0.26.0
    oxlint: ^1.41.0
    reflect-metadata: ^0.2.2
    rxjs: ^7.8.1
    source-map-support: ^0.5.21
    supertest: ^7.0.0
    ts-loader: ^9.5.2
    ts-node: ^10.9.2
    tsconfig-paths: ^4.2.0
    typescript: ^5.7.3
    typescript-eslint: ^8.20.0
    "@vitest/coverage-v8": ^4.0.18
    unplugin-swc: ^1.5.9
    vitest: ^4.0.18
    zod: ^4.3.6
