services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/teax
      REDIS_URL: redis://redis:6379
      NUXT_PUBLIC_APP_URL: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
